name: build on Monterey

on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: macos-12
    steps:
      - name: getting source code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install -e ".[dev]"
      - name: Build
        run: |
          source venv/bin/activate
          ./utils/build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
